# -------- Build Stage --------
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./frontend/

# Install dependencies
WORKDIR /app/frontend
RUN npm install --legacy-peer-deps

# Copy source code
WORKDIR /app
COPY frontend ./frontend
COPY common ./common

# Build application
WORKDIR /app/frontend
RUN npm run build

# -------- Production Stage --------
FROM node:20-alpine

WORKDIR /app

# Copy built app from builder
COPY --from=builder /app/frontend ./

EXPOSE 3000

CMD ["npm", "run", "start"]