version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: inventory_mongo
    ports:
      - "27019:27017"  # host:container
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: inventory_backend
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory_db
      - NODE_ENV=production
      - PORT=8082

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: inventory_frontend
    ports:
      - "7001:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://31.97.115.181:8082/api

volumes:
  mongo_data: