version: "3.9"

services:

  mongo:
    image: mongo:6
    container_name: ${PROJECT_NAME}_mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ${PROJECT_NAME}_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/${DB_NAME}
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ${PROJECT_NAME}_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend

volumes:
  mongo_data: